"use strict";
import { StyleSheet } from "react-native";
const { MAIN_COLOR } = require("../../Constants/Constants.js");
module.exports = StyleSheet.create({
    container:{
        width:100+"%",
        height:100+"%",
        alignItems:'center',
        backgroundColor:"#F0F5F5",
    },
    header:{
        width:"100%",
        height:60,
        backgroundColor:MAIN_COLOR,
        flexDirection:'row',
        borderColor:MAIN_COLOR,
        borderWidth:0.5,
        alignItems:'center',
    },
    header_menu:{
        width:24,
        height:36,
        position:'absolute',
        zIndex:999,
        top:30,
        left:20,
        borderWidth:1,
        borderColor:'#F81C00',
    },
    header_icon:{
        width:24,
        height:36,
    },
    header_container:{
        position:'absolute',
        top:15,
        right:0,
        width:'70%',
        alignItems:'center',
        justifyContent:'space-between',
        flexDirection:'row',
    },
    header_info:{
        alignItems:'center',
    },
    header_title:{
        color:'#FF321A',
        fontSize:19,
        fontWeight:'bold',
    },
    header_button:{
        borderColor:'#F81C00',
    },
    header_button_icon:{
        width:30,
        height:30,
    },
    body:{
        width:"100%",
        flex:1,
        alignItems:'center',
    },
    class_header:{
        width:"100%",
        height:50,
        alignItems:'center',
        justifyContent:'center',
    },
    class_header_text:{
        fontSize:30,
        fontWeight:'bold',
        color:'#FF0000',
    },
    class_info_view:{
        flex:0.5,
        width:"100%",
        marginTop:20,
    },
    horizontal_item_container:{
        flexDirection:'row',
        width:"100%",
        justifyContent:'center',
    },
    horizontal_item:{
        width:"40%",
        alignItems:'center',
        justifyContent:'center',
        height:32,
        flexDirection:'row',
    },
    item_info:{
        width:"100%",
        height:32,
        flexDirection:'row',
        alignItems:'center',
    },
    item_name_title:{
        marginLeft:'20%',
        fontSize:18,
        color:'#A8A8A8',
    },
    item_name:{
        marginLeft:5,
        fontSize:18,
        fontWeight:'bold',
        color:'#000000',
    },
    button_view:{
        borderWidth:1,
        width:"100%",
        flex:1,
        alignItems:'center',
        justifyContent:'space-evenly',
    },
    button_touchable:{
        alignItems:'center',
        justifyContent:'center',
        width:120,
        height:50,
        backgroundColor:'red',
        borderRadius:30,
    },
    button_text:{
        fontSize:16,
        color:'#FFFFFF',
        fontWeight:'bold',
    },
    location_title:{
        justifyContent:'center',
        alignItems:'center',
    },
    location_title_text:{
        fontSize:18,
        fontWeight:'bold',
        color:'#000000',
    },
    location_text:{
        fontSize:17,
        fontStyle:'italic',
        color:'#A9A9A9',
    },
});