"use strict";
import { StyleSheet } from "react-native";
const { MAIN_COLOR } = require("../../Constants/Constants.js");

module.exports = StyleSheet.create({
    container:{
        width:100+"%",
        height:100+"%",
        alignItems:'center',
        backgroundColor:"#F0F5F5",
    },
    header:{
        width:"100%",
        height:60,
        backgroundColor:MAIN_COLOR,
        flexDirection:'row',
        borderColor:MAIN_COLOR,
        borderWidth:0.5,
        justifyContent:'space-between',
        alignItems:'center',
    },
    header_icon:{
        width:24,
        height:36,
    },
    header_menu:{
        borderWidth:1,
        borderColor:'#F81C00',
        marginLeft:20,
        marginTop:30,
    },
    header_info:{
        flexDirection:'row',
        alignItems:'center',
    },
    avatar:{
        width:40,
        height:40,
        borderRadius:25,
    },
    user:{
        marginLeft:15,
    },
    header_text_name:{
        color:"#F81C00",
        fontSize:17,
        fontWeight:'bold',
    },
    header_text_MSSV:{
        color:"#F81C00",
        fontSize:14,
    },
    body:{
        width:"100%",
        flex:1,
        alignItems:'center',
        justifyContent:'center',
    },
    box:{
        width:"100%",
        alignItems:'center',
        flexDirection:'row',
    },
    box_item:{
        alignItems:'center',
        justifyContent:'center',
        width:"50%",
        aspectRatio: 1,
    },
    icon_item:{
        width:"70%",
        height:"70%",
    },
    item_name_text:{
        fontWeight:'bold',
        fontSize:16,
        color:'#000000',
        paddingTop:10,
    },
    item_name_info:{
        fontSize:15,
        width:150,
        textAlign:'center',
    },
    touch_area:{
        backgroundColor:'white',
        width:100,
        height:100,
        borderWidth:2,
        borderColor:'#F81C00',
        borderRadius:30,
        alignItems:'center',
        justifyContent:'center',
    },
});